export const headline = 'TERMS AND CONDITIONS';
export const termsandcontions = [
	{
		title: 'General Provisions',
		desc: "This document establishes the terms and conditions for using the website by the customer, unless the customer has another valid usage agreement between SELF VISION DESIGN SRL, the exclusive owner of www.self-posters.com, and themselves.\n\nUsing the site, including but not limited to accessing, visiting, and viewing content/services, implies the customer's agreement to these terms and conditions. The customer is obligated to regularly monitor these terms which may be updated, modified, or supplemented.\n\nBy using the site/content/service, the customer is solely responsible for all activities resulting from such use. They are also liable for any material, intellectual, or other damages caused to the site/content/service, SELF VISION DESIGN SRL, or any third parties contracted by SELF VISION DESIGN SRL, in accordance with current Romanian legislation.\n\nUsing, including visiting and purchasing products from www.self-posters.com, implies full acceptance of these terms and conditions each time the site is accessed. Please read the Terms and Conditions section carefully before completing an order. To finalize an order, the customer must accept these specified Terms and Conditions. These terms may be changed at any time by the seller without prior notice to the customer.",
	},
	{
		title: 'Our Details',
		desc: 'The following conditions regulate the sale of products presented on this website by:\n\nSELF VISION DESIGN SRL (hereinafter SELF), Bucharest, Romania, registered at the Bucharest Trade Register under no. J40/12914/2024, Tax ID RO50309275',
	},
	{
		title: 'Purchase Guarantee',
		desc: "Each product on this website is accompanied by: product name, product photo, product description, available frames and colors, composition, and price.\n\nProduct colors displayed on screen may vary depending on monitor quality. Current technology doesn't allow printing in RGB format, only CMYK. Therefore, bright colors may print slightly darker. SELF cannot guarantee that colors on screen exactly match real printed colors.\n\nSpecial offers, promotions or discounts are valid until the indicated date or while supplies last. Our product prices may change without prior notice. We reserve the right to modify or discontinue the Service (or any part or content thereof) without notice at any time. We shall not be liable to you or any third-party for any modification, price change, suspension or discontinuance of the Service.",
	},
	{
		title: 'Ordering',
		desc:
			'The Customer/User can place orders on the site by adding desired products to the shopping cart, then completing the order by payment through one of the methods indicated on the site.\n\nPayment methods accepted by SELF VISION DESIGN SRL are Visa, Mastercard payments, with Google and Apple Pay also available, managed through the Stripe payment processor.' +
			"Once added to the shopping cart, a product is available for purchase only if stock exists. Adding a product to the cart without completing the order doesn't register the order or automatically reserve the product.\n\nBy completing the order, the customer agrees that all provided data necessary for the purchase process is correct, complete and true at the time of ordering.\n\nBy completing the order, the customer agrees that SELF VISION DESIGN SRL may contact them through any available/agreed means when necessary.\n\nSELF may unilaterally cancel the customer's order after prior notification, without any further obligation between parties or claims for damages in the following cases:\n\n- rejection of the transaction by the customer's card-issuing bank for online payments; transaction invalidation by SELF's payment processor for online payments; incomplete or incorrect customer data provided on the site;\n\n- customer activity on the site may cause damages of any kind, or prejudice SELF and/or its partners;\n\n- more than two consecutive failed delivery attempts;\n\nThe invoice will be issued based on data provided by the customer when placing the order. SELF is not responsible for incorrect, incomplete, or false data provided by the customer when placing the order.\n\nWe recommend customers verify all data provided to SELF that will be used for invoicing.\n\n",
	},
	{
		title: 'Delivery',
		desc: "Delivery of purchased products to customers is performed by our courier partner Sameday. The courier company processes SELF customer personal data exclusively for transporting purchased products from our website, strictly in compliance with these Terms and Conditions. Third parties mandated by the courier company to perform delivery services must also fully comply with data protection laws and these Terms and Conditions. In this regard, the courier company may contact SELF customers through any communication means (email, phone, SMS) within the limits and purposes stated in this article.\n\nOrders are shipped from our Bucharest headquarters and typically arrive within 4-5 business days from order registration.\n\nAll orders registered in our system are shipped within maximum three business days after order placement.\n\nDelivery times may vary depending on order volume. We are not responsible for potential delays during promotional periods.\n\nSELF is responsible for proper product packaging and will ensure transmission of accompanying documents for product delivery.\n\nSELF delivers Products and provides Services only within Romania.\n\nIf SELF cannot fulfill the contract because a product is unavailable, SELF will inform the customer.\n\nDelivery details, including but not limited to delivery time, don't constitute a contractual obligation from SELF, and neither party may claim damages if either party is prejudiced by their violation.\n\n",
	},
	{
		title: 'Product Ownership Transfer',
		desc: 'Unless otherwise agreed between Self Posters and the customer, product ownership transfers upon delivery, after customer payment at the location specified in the order (with delivery meaning the signing of receipt for the transport document provided by the courier).\n\n',
	},
	{
		title: 'Returns',
		desc: "Personalized products cannot be returned according to \"Emergency Ordinance 34/2014 Article 16 point c\" except in the following situations:\n- packages with severe damage or products with manufacturing defects.\n- packages that don't match aesthetically (with visible damage) will be refused. To avoid misunderstandings, the package should be photographed and a report should be completed with the courier company representative specifying the package's condition.\n- products were delivered or invoiced incorrectly; if products are delivered incorrectly (personalized with third-party data), the CUSTOMER must promptly notify SELF to remedy the situation and follow SELF's instructions exactly (return/destruction of third-party information), having no rights over data/products that don't belong to them.\n- products have incorrect specifications on the website compared to reality.\n\nThe consumer has the right to unilaterally terminate the distance contract without penalties and without giving a reason within 14 business days of receiving the product or, for services, from contract conclusion, except for personalized products which cannot be returned according to Emergency Ordinance 34/2014 Article 16 point c. The only costs that may fall to the consumer are direct return shipping costs according to G.O. 130/2000 and amendments in OUG 34/2014, for individuals purchasing products from websites using distance communication techniques, applying definitions contained in G.O. 34/2014 art. 16. Returned products should be in original packaging when possible, with all accessories and documents, without any signs of damage or wear, must be new, unworn or unused in any way (washed, perfumed, etc.), and complete (with all accessories and tags). Product damage or making them unsellable leads to return refusal.\n\nThe CUSTOMER must notify SELF of their intention to return purchased products by completing the return form within maximum 14 business days of receiving the products and communicating this to SELF.\n\nIf the purchased product has manufacturing defects, it will be replaced with a new product, provided SELF is notified in writing within 14 days of product receipt. If replacement isn't possible, the value will be refunded or another product may be purchased.\n",
	},
	{
		title: 'Liability',
		desc: 'Self Posters cannot be liable for any damages that the customer or any third party may suffer as a result of SELF fulfilling any of its obligations under the order, or for damages resulting from product use after delivery, and especially for their loss\n',
	},
	{
		title: 'Applicable Law',
		desc: 'Any disputes regarding contract execution will be resolved amicably between Seller and Customer, otherwise the parties may address competent Romanian courts in Bucharest.',
	},
];
