export const headline = 'TERMENI ȘI CONDIȚII';
export const termsandcontions = [
	{
		title: 'Aspecte generale',
		desc:
			'Documentul stabilește termenii și condițiile de utilizare a site-ului de către client, în cazul în care acesta nu dispune de un alt acord de utilizare valid, încheiat între SELF VISION DESIGN SRL, societate în proprietatea exclusivă a căreia se află site-ul www.selfposters.ro și acesta.\n\nFolosirea, inclusiv dar nelimitându-se la accesarea, vizitarea și vizualizarea, conținutului / serviciului, ' +
			'implică aderarea clientului la prezentele termeni și condiții. Clientul se obligă să monitorizeze permanent termenii și condițiile care pot fi actualizate, modificate și completate.\n\nPrin folosirea site-ului / conținutului / serviciului, clientul este singurul responsabil pentru toate activitățile care decurg prin folosirea acestuia. De asemenea, acesta răspunde pentru orice daune materiale sau intelectuale sau de orice altă natură produse site-ului / conținutului / serviciului, SELF VISION DESIGN SRL sau oricărui terț cu care SELF VISION DESIGN SRL, are încheiate contracte, în conformitate cu legislația română în vigoare.\n\nFolosirea, inclusiv vizitarea și cumpărarea produselor de pe site-ul www.selfposters.ro, presupune acceptarea în totalitate și de fiecare dată când se accesează site-ul, a termenilor și condițiilor sub care sunt furnizate aceste servicii și produse. Te rugăm să citești cu atenție secțiunea Termeni și condiții, pentru a fi în cunoștință de cauză în momentul în care finalizezi o comandă. Pentru a putea finaliza o comandă, clientul trebuie să accepte Termenii și condițiile specificate. Termenii și condițiile acestor servicii pot fi schimbate în orice moment de către vânzător, fără a fi necesară o notificare prealabilă a clientului.',
	},
	{
		title: 'Datele noastre',
		desc: 'Următoarele condiții reglementează vânzarea de produse prezentate pe această pagină web de către societatea:\n\nSELF VISION DESIGN SRL (denumită în continuare SELF), București, România, înregistrată la Registrul Comerțului București sub nr. J40/12914/2024, CUI 50309275',
	},
	{
		title: 'Garanția de cumpărare',
		desc: 'Fiecare produs de pe acest website este însoțit de următoarele detalii: denumirea produsului, fotografia produsului, descrierea produsului, rame și culori disponibile, compoziție, preț.\n\nCuloarea produselor se afișează pe ecran poate suferi modificări, în funcție de calitatea monitorului computerului. Tehnologia actuală nu permite printarea culorilor în format RGB, ci CMYK. Astfel, culorile stridente pot ieși la imprimare ușor mai închise. Prin urmare, SELF nu poate garanta că culorile care apar pe monitor sunt o reprezentare fidelă a culorilor reale. Ofertele speciale, promoțiile sau reducerile sunt valabile până la data indicată sau până la epuizarea stocurilor. Prețurile pentru produsele noastre pot fi modificate fără notificare prealabilă. Ne rezervăm dreptul în orice moment de a modifica sau întrerupe Serviciul (sau orice parte sau conținut al acestuia) fără notificare în orice moment. Nu vom fi răspunzători față de dvs. sau față de terți pentru orice modificare, modificare a prețului, suspendarea sau întrerupere a Serviciului.',
	},
	{
		title: 'Comanda',
		desc:
			'Clientul/Utilizatorul poate efectua comenzi pe site prin adăugarea produselor dorite în coșul de cumpărături, urmând a finaliza comanda, efectuând plata prin una dintre modalitățile indicate pe site.\n\nModalitatea de plată acceptată de către SELF VISION DESIGN SRL este plata cu cardul bancar Visa, Mastercard, având la îndemână și folosirea Google și Apple Pay, gestionată cu ajutorul intermediarului de plată Stripe.' +
			'Odată adăugat în coșul de cumpărături, un produs  este disponibil pentru achiziție în măsura în care există stoc disponibil pentru acesta. Adăugarea unui produs în coșul de cumpărături, în lipsa finalizării comenzii, nu atrage după sine înregistrarea comenzii, implicit nici rezervarea automată a produsului.\n\nPrin finalizarea comenzii, clientul consimte că toate datele furnizate de acesta, necesare procesului de cumpărare, sunt corecte, complete si adevărate la data plasării comenzii, denumită în cadrul acestui document și comanda emisa.\n\nPrin finalizarea comenzii, clientul consimte că SELF VISION DESIGN SRL îl poate contacta prin orice mijloc disponibil/agreat de SELF VISION DESIGN SRL, în orice situație în care este necesară contactarea clientului.\n\nSELF poate denunța unilateral comanda efectuată de către client, în urma unei notificări prealabile adresate clientului, fără nicio obligație ulterioară a vreunei parți față de cealaltă sau fără ca vreo parte să poată să pretindă celeilalte daune-interese în următoarele cazuri:\n\n- neacceptarea de către banca emitentă a cardului clientului, a tranzacției, în cazul de plăți online; invalidarea tranzacției de către procesatorul de carduri agreat de SELF, în cazul plății online; datele furnizate de către client, pe site sunt incomplete sau incorecte;\n\n- activitatea clientului pe site poate și/sau produce daune de orice natură, sau prejudiciază în orice fel SELF și/sau partenerii acestuia;\n\n- realizarea a mai mult de două livrări consecutive, esuate;\n\nFactura se va emite pe baza datelor furnizate de către client prin comanda plasată. SELF nu este responsabil și nu poate fi ținut răspunzător pentru furnizarea unor date incorecte, incomplete și/sau neadevărate la data plasării comenzii de către client.\n\nRecomandăm clienților să verifice datele furnizate către SELF în baza cărora se va emite factura aferentă comenzilor.\n\n',
	},
	{
		title: 'Livrare',
		desc: 'Livrarea către client a produselor achiziționate este efectuată prin intermediul firmei de curierat rapid Sameday. Firma de curierat rapid prelucrează date cu caracter personal ale clientului SELF, exclusiv pentru prestarea serviciilor de transport a produselor achiziționate de aceștia de pe website-ul companiei și numai cu respectarea întocmai a prezentului document Termeni și Condiții SELF. De asemenea, terții parteneri ai firmei de curierat rapid, mandatați pentru îndeplinirea serviciilor de transport, care procesează date cu caracter personal ale clienților SELF, sunt ținuți la respectarea întocmai a termenilor și condițiilor legii cu privire la siguranța prelucrării datelor cu caracter personal și a prezentului document Termeni și Condiții SELF. În acest sens, firma de curierat rapid poate contacta clienții SELF prin orice mijloc de comunicare (e-mail, telefon, SMS) în limitele și în scopul prevăzut în prezentul articol.\n\nComenzile sunt livrate de la sediul nostru din București și ajung la destinație în interval de 4-5 zile lucrătoare de la înregistrarea comenzii.\n\nToate comenzile înregistrate în sistemul nostru sunt expediate în maxim trei zile lucrătoare după ziua plasării comenzii.\n\nTimpul de livrare poate varia în funcție de volumul de comenzi înregistrate. Nu ne asumăm răspunderea pentru eventuale întârzieri în perioadele cu promoții/reduceri.\n\nSELF își asumă responsabilitatea pentru ambalarea corespunzătoare a produselor și va asigura transmiterea documentelor însoțitoare în vederea livrării produselor.\n\nSELF efectuează livrarea Produselor și prestarea Serviciilor numai pe teritoriul României.\n\nÎn cazul în care SELF nu poate executa contractul din cauza că produsul nu este disponibil, SELF va informa clientul despre această situație.\n\nDetaliile de livrare a produselor, incluzând, dar nelimitându-se la timpul necesar livrării, nu constituie o obligație contractuală din partea SELF, fără ca vreo parte să poată pretinde celeilalte daune-interese, în cazul în care oricare dintre părți poate fi sau este prejudiciată în orice mod de pe urma încălcării acestora.\n\n',
	},
	{
		title: 'Transferul proprietății produselor',
		desc: 'În afara de cazul în care este agreat de către Self Posters și client diferit, proprietatea asupra produselor va fi transferată la livrare, după efectuarea plății din partea clientului în locația indicată în comandă (înțelegând prin livrare – semnarea de primire a documentului de transport furnizat de către curier).\n\n',
	},
	{
		title: 'Retur',
		desc: 'Produsele personalizate nu se pot returna conform „Ordonanței de Urgență 34/2014 din 04.06.2014 articolul 16 punctul c” decât în următoarele situații:\n- coletele prezintă deteriorări severe sau produsele prezintă defecte de fabricație.\n- coletele ce nu corespund din punct de vedere estetic (care prezintă deteriorări evidente) vor fi refuzate. Pentru a se evita neînțelegerile, coletul va fi fotografiat și se va întocmi împreună cu reprezentantul firmei de curierat un proces verbal în care se va specifica starea coletului.\n- produsele au fost livrate sau facturate greșit; în cazul în care produsele sunt livrate greșit (produsele sunt personalizate cu datele unor terți), CLIENTUL va notifica SELF cu promptitudine în vederea remedierii situației și va urma întocmai instrucțiunile comunicate de către SELF (returul/distrugerea informațiilor cu privire la terții respectivi), neavând niciun drept asupra datelor/produselor respective care nu-i aparțin.\n- produsele au specificații eronate pe site față de realitate.\n\nConsumatorul are dreptul de a denunța unilateral contractul la distanță, fără penalități și fără invocarea unui motiv, în termen de 14 zile lucrătoare de la primirea produsului sau, în cazul prestărilor de servicii, de la încheierea contractului, cu excepția produselor personalizate care nu pot fi returnate conform Ordonanței de Urgență 34/2014 din 04.06.2014 articolul 16 punctul c. Furnizarea de produse confecționate după specificațiile prezentate de consumator sau personalizate în mod clar. Singurele costuri care pot cădea în sarcina consumatorului sunt cheltuielile directe de returnare a produselor conf. O.G. 130/2000 și modificările din OUG 34/2014, pentru persoanele fizice ce achiziționează produse de pe site-uri, folosind tehnicile de comunicare la distanță, aplicându-se definițiile cuprinse în O.G. 34/2014 art. 16. Returnarea produselor trebuie să se facă pe cât este posibil în ambalajul original, dar cu toate accesoriile și documentele și fără să prezinte nici o urmă de deteriorare sau uzură, trebuie să fie noi, fără să fi fost purtate sau folosite de niciun fel (spălate, impregnate cu parfum sau odorizante de cameră etc.), trebuie să fie complete (împreună cu toate accesoriile și etichetele sale). Deteriorarea produselor sau punerea într-o stare de nevandabilitate duce la refuzarea returului.\n\nCLIENTUL este obligat să notifice SELF intenția sa de a returna produsele achiziționate, completând formularul de retur în termen de maxim 14 zile lucrătoare de la primirea produselor și comunicarea acestui fapt către SELF.\n\nÎn eventualitatea în care produsul achiziționat prezintă vicii de fabricație, acesta va fi înlocuit cu un produs nou, cu condiția notificării în scris a SELF în termen de 14 zile de la recepționarea produsului. Dacă înlocuirea nu este posibilă, se va returna contravaloarea lui sau se poate achiziționa un alt produs.\n',
	},
	{
		title: 'Responsabilitate',
		desc: 'Self Posters nu poate fi responsabil pentru daune de orice fel pe care clientul sau orice terță parte le poate suferi ca rezultat al îndeplinirii de către SELF a oricăreia dintre obligațiile sale conform comenzii și pentru daune care rezultă din utilizarea produselor după livrare și, în special, pentru pierderea acestora\n',
	},
	{
		title: 'Legea Aplicabilă',
		desc: 'Eventualele litigii în legătură cu executarea contractului vor fi rezolvate între Vânzător și Client pe cale amiabilă, în caz contrar, părțile putându-se adresa instanțelor judecătorești române competente din Municipiul București.',
	},
];
